### ISSUE TITLE
The documentation links to the wrong Terraform module?

### ISSUE THREAD

**Issue by medicinal-matt** [snowplow-devops/terraform-aws-collector-kinesis-ec2#10]
I tried to follow the official documentation on how to setup the Snowplow collector using Terraform. However the page [Set up the stream collector](https://docs.snowplowanalytics.com/docs/pipeline-components-and-applications/stream-collector/setup/) links to [snowplow-devops/iglu-server-ec2](https://registry.terraform.io/modules/snowplow-devops/iglu-server-ec2/aws/latest), but surely it is supposed to be [snowplow-devops/collector-kinesis-ec2](https://registry.terraform.io/modules/snowplow-devops/collector-kinesis-ec2/aws/latest)?

**Comment by jbeemster** [comment]
Thanks for flagging @medicinal-matt that does seem like a bug in the docs!  We will get that fixed.

**Comment by jbeemster** [comment]
@paulboocock is that something you can fix up?

**Comment by paulboocock** [comment]
Fixed. Thanks @medicinal-matt!
