### ISSUE TITLE
Clarify ssh_key_name should be an existing key

### ISSUE THREAD

**Issue by medicinal-matt** [snowplow-devops/terraform-aws-collector-kinesis-ec2#12]
The current documentation of the ssh_key_name variable just mentions

`variable "ssh_key_name" {
  description = "The name of the SSH key-pair to attach to all EC2 nodes deployed"
  type        = string
}`

It should probably also mention that this key needs to be created in advance for the apply to work. Otherwise you get "ValidationError: The key pair 'name' does not exist"

**Comment by jbeemster** [comment]
@medicinal-matt - appreciating all of this feedback!  As we are not asking for a public-key I would assume this is self-explanatory?  The validation error makes it straightforward to figure out next steps as well.

How would you re-phrase it?

**Comment by medicinal-matt** [comment]
Maybe "The name of the **preexisting** SSH key-pair to attach to all EC2 nodes deployed" for us absolute beginners. I thought it would generate it for me. ;)

**Comment by medicinal-matt** [comment]
I created a pull request https://github.com/snowplow-devops/terraform-aws-collector-kinesis-ec2/pull/13
