### ISSUE TITLE
[Doubt] Bad Stream

### ISSUE THREAD

**Issue by KleyLimaa** [snowplow-devops/terraform-aws-collector-kinesis-ec2#23]
I have a doubt with if there's some moment where collector send data to bad stream, because as far as I understand the collector don't make validations. I am missing something or the bad stream parameter was just created as copy/paste from other modules?

Thanks in advance

**Comment by jbeemster** [comment]
Hey @KleyLimaa - so it's rare but it is definitely possible.  If the event received by the collector is too big for the downstream destination you will get an oversized event bad row.

For Kinesis this is 1megabit per record.

**Comment by KleyLimaa** [comment]
Okay, its clear now, thanks for the time!
